version: "3.8"

services:
  app:
    build: .
    ports:
      - "8090:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my-network

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: poladiaraj
      POSTGRES_USER: poladiaraj
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Host:Container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poladiaraj"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Optional but recommended

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
